name: Scheduled Workflow

# Trigger workflow using a schedule
on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  scheduled-task:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run a custom task
      - name: Run a script
        run: echo "This workflow runs every 5 minutes!"
